function AboutDIRART()
uiwait(msgbox(sprintf([...
	'DIRART Suite\n\n' ...
	'For Deformable Image Registration and Adaptive Radiotherapy Research\n\n'...
	'For research purposes only, not for clinical treatments\n\n'...
	'Version 1.0a (Feb. 2009)\n\n'...
	'Deshan Yang, PhD, 2006-2009\n'...
	'email: dyang@radonc.wustl.edu\n\n'...
	'Department of Radiation Oncology\n'...
	'School of Medicine\n'...
	'Washington University in St Louis, MO, USA']),...
	'About DIRART Suite','modal'));

