function FirstHelp()
%
%	FirstHelp()
%

uiwait(msgbox(sprintf([...
	'Ways to start:\n\n' ...
	'1) Load two image sets using File->Load Images->...\n' ...
	'   or   \n' ...
	'2) Load previously saved projects using File->Load Project ...\n' ...
	]),...
	'First Help','modal'));


